import {
  GridColDef,
  GridRowId,
  GridStateColDef,
  GridValueGetterSimpleParams,
} from '../../../models';

export const getGroupingColDefField = (groupedByField: string | null) => {
  if (groupedByField === null) {
    return '__row_group_by_columns_group__';
  }

  return `__row_group_by_columns_group_${groupedByField}__`;
};

export const getCellValue = ({
  colDef,
  id,
  row,
  isAutoGenerated,
}: {
  colDef: GridColDef | GridStateColDef;
  id: GridRowId;
  row: any;
  isAutoGenerated: boolean | undefined;
}) => {
  if (colDef.valueGetter) {
    const params: GridValueGetterSimpleParams = {
      colDef,
      field: colDef.field,
      id,
      row,
      rowNode: {
        isAutoGenerated,
        id,
      },
    };
    return colDef.valueGetter(params);
  }

  return row[colDef.field];
};
