import { GridColDef } from '../../../models/colDef/gridColDef';
import { GRID_STRING_COL_DEF } from '../../../models/colDef/gridStringColDef';
import { GridRowGroupByColumnsGroupingCellValue } from '../../../components/cell/GridRowGroupByColumnsGroupingCell';
import { gridFilteredDescendantCountLookupSelector } from '../filter';

export const GRID_ROW_GROUP_BY_COLUMNS_GROUP_COL_DEF: Omit<GridColDef, 'field'> = {
  ...GRID_STRING_COL_DEF,
  type: 'rowGroupByColumnsGroup',
  sortable: false,
  filterable: false,
  disableColumnMenu: true,
  disableReorder: true,
  align: 'left',
  width: 200,
  valueGetter: ({ rowNode, api }): GridRowGroupByColumnsGroupingCellValue => ({
    label: rowNode.groupingValue.toString(),
    depth: rowNode.depth,
    expanded: rowNode.expanded ?? false,
    isAutoGenerated: rowNode.isAutoGenerated ?? false,
    filteredDescendantCount: gridFilteredDescendantCountLookupSelector(api.state)[rowNode.id] ?? 0,
  }),
};
